{-# LANGUAGE QuasiQuotes #-}
module Handler.BlackList ( getBlackListR ) where

import           Import


getBlackListR :: Handler Html
getBlackListR = defaultLayout $ do
    setAppPageTitle MsgBlackList
    [whamlet|
        <h5 .mb-5>_{MsgPrizmBlackListTitle}
        <table .table .table-striped .table-hover .table-sm .table-hover>
            <thead>
                <tr>
                    <th>
                        _{MsgWalletAddress}
                    <th>_{MsgCard}
                    <th>_{MsgPhone}
                    <th>_{MsgSkype}
                    <th>_{MsgTelegramTitle}
                    <th>_{MsgWebSite}
                    <th>_{MsgVkComTitle}
            <tbody>
                <tr>
                    <td>
                        PRIZM-N67D-F8DX-JWZL-59MKT
                    <td>
                        4 276 021 155 299 480
                    <td>
                        89130216405
                    <td>
                        live:bodyaa1990
                    <td>
                        Say Braah
                    <td>
                        cryptohome.su
                    <td>
                        <a
                            href="https://vk.com/id132167501"
                            target="_blank">
                            id132167501
                <tr>
                    <td>
                        PRIZM-437P-ZHST-6WHB-3FQXU
                    <td>
                        5469300506886131
                    <td>
                        79020953007
                    <td>
                    <td>
                    <td>
                    <td>
                        <a
                            href="https://vk.com/id114515093"
                            target="_blank">
                            id114515093
                <tr>
                    <td>
                        PRIZM-SKXY-62EZ-AAEC-Z64Y4
                    <td>
                    <td>
                        79020953007
                    <td>
                    <td>
                    <td>
                    <td>
                        <a
                            href="https://vk.com/id114515093"
                            target="_blank">
                            id114515093
                <tr>
                    <td>
                        PRIZM-QMVV-YE96-9W2Z-D4QRG
                    <td>
                    <td>
                        8913021640
                    <td>
                    <td>
                    <td>
                    <td>
                        <a
                            href="https://vk.com/max.polkovnikov"
                            target="_blank">
                            max.polkovnikov
                <tr>
                    <td>
                        PRIZM-N67D-F8DX-JWZL-59MKT
                    <td>
                    <td>
                        8 913 264 80 86
                    <td>
                    <td>
                    <td>
                    <td>
                        <a
                            href="https://vk.com/id480538496"
                            target="_blank">
                            id480538496
                <tr>
                    <td>
                        PRIZM-N67D-F8DX-JWZL-59MKT
                    <td>
                    <td>
                        83852580826
                    <td>
                    <td>
                    <td>
                    <td>
                        <a
                            href="https://vk.com/id270094735"
                            target="_blank">
                            id270094735
                <tr>
                    <td>
                         PRIZM-THG8-HSFG-EM46-AVX9H
                    <td>
                    <td>
                        79184726508
                    <td>
                    <td>
                    <td>
                    <td>
                        <a
                            href="https://vk.com/id474387846"
                            target="_blank">
                            id474387846
                <tr>
                    <td>
                        PRIZM-EB4N-EJCR-GBHF-9JUGP
                    <td>
                    <td>
                        79132648086
                    <td>
                    <td>
                    <td>
                    <td>
                        <a
                            href="https://vk.com/id492225270"
                            target="_blank">
                            id492225270
                <tr>
                    <td>
                        PRIZM-NRK8-CHUU-95L7-87H7S
                    <td>
                    <td>
                        89110898774
                    <td>
                    <td>
                    <td>
                    <td>
                        <a
                            href="https://vk.com/id425629439"
                            target="_blank">
                            id425629439
                <tr>
                    <td>
                        PRIZM-RGR2-V9F6-HHGJ-243ZV
                    <td>
                    <td>
                    <td>
                    <td>
                    <td>
                    <td>
                        <a
                            href="https://vk.com/prizmexchange"
                            target="_blank">
                            prizmexchange
                <tr>
                    <td>
                        PRIZM-69VQ-Y6FH-CC9E-5CLL5
                    <td>
                    <td>
                    <td>
                    <td>
                    <td>
                    <td>
                        <a
                            href="https://vk.com/id460832995"
                            target="_blank">
                            id460832995
                <tr>
                    <td>
                        PRIZM-DHR8-5CWD-YUUK-PTGKH
                    <td>
                    <td>
                    <td>
                    <td>
                    <td>
                    <td>
                        <a
                            href="https://vk.com/prizm_money"
                            target="_blank">
                            prizm_money
                <tr>
                    <td>
                        PRIZM-9HPX-B4MZ-KWQV-DD7TM
                    <td>
                    <td>
                    <td>
                    <td>
                    <td>
                    <td>
                        <a
                            href="https://vk.com/id499850359"
                            target="_blank">
                            id499850359
                <tr>
                    <td>
                        PRIZM-L7NN-CHWU-689H-3UKLE
                    <td>
                    <td>
                    <td>
                    <td>
                    <td>
                    <td>
                        <a
                            href="https://vk.com/id299638545"
                            target="_blank">
                            id299638545
                <tr>
                    <td>
                        PRIZM-RQCA-H4RB-27VN-A395F
                    <td>
                    <td>
                    <td>
                    <td>
                    <td>
                    <td>
                        <a
                            href="https://vk.com/osokrovis"
                            target="_blank">
                            osokrovis
                <tr>
                    <td>
                        PRIZM-N86J-U29T-JT24-79DK6
                    <td>
                    <td>
                    <td>
                    <td>
                    <td>
                    <td>
                        <a
                            href="https://vk.com/id470346638"
                            target="_blank">
                            id470346638
                <tr>
                    <td>
                        PRIZM-6L68-MBUC-RYXN-RNQF9
                    <td>
                    <td>
                    <td>
                    <td>
                    <td>
                    <td>
                        <a
                            href="https://vk.com/club171165926"
                            target="_blank">
                            club171165926
                <tr>
                    <td>
                        PRIZM-YDPH-PGVL-8FHD-7SHP5
                    <td>
                    <td>
                    <td>
                    <td>
                    <td>
                    <td>
                        <a
                            href="https://vk.com/id29899968"
                            target="_blank">
                            id29899968
                <tr>
                    <td>
                        PRIZM-ZC2X-7SHZ-ME7R-3LPH9
                    <td>
                    <td>
                    <td>
                    <td>
                    <td>
                    <td>
                        <a
                            href="https://vk.com/id491753669"
                            target="_blank">
                            id491753669
                <tr>
                    <td>
                        PRIZM-PSJ9-3EEY-JY57-R74N8
                    <td>
                    <td>
                    <td>
                    <td>
                    <td>
                    <td>
                        <a
                            href="https://vk.com/id500612377"
                            target="_blank">
                            id500612377
                <tr>
                    <td>
                        PRIZM-4GR6-QFEE-FJJQ-AL4DA
                    <td>
                    <td>
                    <td>
                    <td>
                    <td>
                    <td>
                        <a
                            href="https://vk.com/ignatov_ke"
                            target="_blank">
                            ignatov_ke
                <tr>
                    <td>
                        PRIZM-V97N-DUHN-N4K4-BBBT9
                    <td>
                    <td>
                    <td>
                    <td>
                    <td>
                    <td>
                        <a
                            href="https://vk.com/ignatov_konstantin_e"
                            target="_blank">
                            ignatov_konstantin_e
                <tr>
                    <td>
                        PRIZM-J9TE-5Y2H-3XNT-BBUYX
                    <td>
                    <td>
                    <td>
                    <td>
                    <td>
                    <td>
                        <a
                            href="https://vk.com/id488698065"
                            target="_blank">
                            id488698065
                <tr>
                    <td>
                        PRIZM-D7Q3-8M2Z-NMVR-95JX4
                    <td>
                    <td>
                    <td>
                    <td>
                    <td>
                    <td>
                        <a
                            href="https://vk.com/id13790536"
                            target="_blank">
                            id13790536
        |]
