ProjectName: OutBirds

# ACCESS
WrongRequest: Неверный запрос
PleaseLogInText: Пожалуйста, войдите в систему для просмотра этой страницы

# PAGE TITLES
## COMMON
HomePageTitle: Главная страница
SignInPageTitle: Вход
SignUpPageTitle: Регистрация

## CLIENT
ClientProfilePageTitle: Мой портфель
ClientOrdersPageTitle: Мои ордера
ClientDepositPageTitle: Пополнение счёта
ClientWithdrawalPageTitle: Вывод средств


User: Пользователь
EmailAddress: Адрес эл.почты
Password: Пароль
PasswordConfirmation: Подтверждение пароля
Support: Тех.поддержка
Save: Сохранить
Cancel: Отмена
ChangesSaved: Изменения сохранены
AccessDenied: Недостаточно прав доступа

IAcceptTemrsOfUseText: регистрируясь, я принимаю правила и условия использования сервиса

All: Все
Add: Добавить
Manage: Управление
NoPublicationsYet: Публикаций пока не было
NoOperationsYet: Операций не было
OperationDepositShort: Ввод
OperationExchangeShort: Обмен
OperationWithdrawShort: Вывод
CreateRequest: Создать заявку

Date: Дата
DateCreated: Дата создания
Details: Подробности

Ratio: Курс

# ORDERS

Order: Ордер
OrderView: Просмотр ордера
OrderHistory: История ордера
OrderCreated: Создание ордера
OrderWasExecuted: Закрытие ордера
OrderIsNew: Новый
OrderWasCreated: Создан
OrderIsActive: Активен
OrderCancelled: Отменён
OrderWasCancelled: Ордер отменён
OrderCancellation: Отмена ордера
OrderClosed: Закрыт
OrderExecuted: Исполнен
OrderExecution: Исполнение ордера
OrderStatusExecution: Исполняется
OrderLastOperation: Последняя операция
OrderActualIncome: С учётом комиссии
AllOrders: Все ордера
ActiveOrders: Активные
ExecutedOrders: Выполненые
ViewOrderDetails: Просмотр истории ордера
CancelOrder: Отменить ордер
CancelOrderConfirmationText: Вы уверены, что хотите отменить ордер на обмен?


Balance: Баланс
Event: Событие
Exchange: Обмен
Execute: Исполнить
Executed: Исполнено
Fee: Комиссия
IExchange: Обмениваю
Received: Получено
Remainder: Остаток
Withdraw: Вывод
Deposit: Пополнение
Amount: Сумма
QuantityShort: Кол-во


# DEPOSIT / WITHDRAWAL

Request: Заявка
BalanceDeposit: Пополнение счёта
DepositRealAmount: К зачислению
DepositConfirmTransfer: Подтвердить перевод
AwaitingConfirmation: Ожидает подтверждения
DepositRequestConfirmedMessage: Заявка подтверждена
DepositRequestAlreadyConfirmed: Заявка уже подтверждена
DepositConfirmed: Подтверждён
DepositConfirmCancellationText: Вы уверены, что хотите отменить заявку на ввод средств?
DepoistCancelled: Пополнение отменено
WithdrawalCancelled: Вывод средств отменён
DepositExecuted: Средства зачислены
DepositRejected: Отклонён
AwaitingExecution: Ожидает исполнения
RequestProcessing: В обработке
BalanceWithdrawal: Вывод средств
BalanceReturn: Возврат средств
ViewRequestDetails: Просмотр подробностей заявки
AmountFrozen: Удержано средств
CantViewThisOrder: Невозможно отобразить данные ордера
ViewOrderHistory: Показать историю ордера
CancelRequest: Отменить заявку
UserCancelled: Отменён пользователем


ProcessRequest: Обработать запрос
TransferMethod: Способ перевода
ExpectedCalculation: Ожидаемый расчёт
ActualCalculation: Расчёт по факту

# OPERATORS
DepositRequestAcceptFormStatsTitle: Расчёт заявки
DeclineRequestTitle: Отмена заявки
DeclineRequest: Отклонить заявку
DeclineReason: Причина отмены

WithdrawalExecuted: Перевод выполнен

TMSberBankCard2Card: СберБанк
TMTinkoffBankCard2Card: Тинькофф Банк
TMAlphaBankCard2Card: Альфа Банк
TMPayPalTransfer: PayPal
TMQiwi: Qiwi кошелёк
TMCryptoTransfer: Перевод

BlackList: Чёрный список
PrizmBlackListTitle: Список Prizm-кошельков, уличённых в мощеничестве

Info: Инфо
InfoListTitle: Информация
Alias: Ссылка
Title: Заголовок
ArticeContent: Текст статьи
NewArticle: Новая статья

TermsOfUse: Правила
TermsOfUseTitle: Правила пользования сервисом


WalletAddress: Адрес кошелька
Card: Карта
Phone: Телефон
Skype: Skype
TelegramTitle: Telegram
WebSite: Веб.сайт
VkComTitle: ВКонтакте


# MISC COMMON PHRASES
InFact: по факту