ProjectName: OutBirds
User: Пользователь
EmailAddress: Адрес эл.почты
Password: Пароль
PasswordConfirmation: Подтверждение пароля
Support: Тех.поддержка
Save: Сохранить
ChangesSaved: Изменения сохранены
AccessDenied: Недостаточно прав доступа

IAcceptTemrsOfUseText: регистрируясь, я принимаю правила и условия использования сервиса


All: Все
Add: Добавить
Manage: Управление
NoPublicationsYet: Публикаций пока не было
NoOperationsYet: Операций не было
OperationDepositShort: Ввод
OperationExchangeShort: Обмен
OperationWithdrawShort: Вывод
CreateRequest: Создать заявку

Date: Дата
DateCreated: Дата создания
Details: Подробности

Order: Ордер
MyOrders: Мои ордера

OrderView: Просмотр ордера
OrderHistory: История ордера
OrderCreated: Создание ордера
OrderWasExecuted: Закрытие ордера
OrderIsNew: Новый
OrderWasCreated: Создан
OrderIsActive: Активен
OrderCancelled: Отменён
OrderWasCancelled: Ордер отменён
OrderCancellation: Отмена ордера
OrderClosed: Закрыт
OrderExecuted: Исполнен
OrderExecution: Исполнение ордера
OrderStatusExecution: Исполняется
OrderLastOperation: Последняя операция
OrderActualIncome: С учётом сборов

AllOrders: Все ордера
ActiveOrders: Активные
ExecutedOrders: Выполненые
ViewOrderDetails: Просмотр истории ордера
CancelOrderConfirmationText: Вы уверены, что хотите отменить ордер на обмен?


Balance: Баланс
Event: Событие
Exchange: Обмен
Execute: Исполнить
Executed: Исполнено
Fee: Сервисный сбор
IExchange: Обмениваю
Rate: Ставка
Received: Получено
Remainder: Остаток
Withdraw: Вывод
Deposit: Пополнение

Request: Заявка
BalanceDeposit: Пополнение счёта
DepositAmount: Сумма
DepositRealAmount: К зачислению
DepositConfirmTransfer: Подтвердить перевод
AwaitingConfirmation: Ожидает подтверждения
DepositConfirmed: Подтверждён
DepositExecuted: Средства зачислены
AwaitingExecution: Ожидает исполнения
BalanceWithdrawal: Вывод средств
ViewRequestDetails: Просмотр подробностей заявки

CantViewThisOrder: Невозможно отобразить данные ордера
ViewOrderHistory: Показать историю ордера

CancelOrder: Отменить ордер
UserCancelled: Отменён пользователем


ProcessRequest: Обработать запрос
TransferMethod: Способ перевода
ExpectedCalculation: Ожидаемый расчёт
ActualCalculation: Расчёт по факту

DepositRequestAcceptFormStatsTitle: Расчёт заявки

WithdrawalExecuted: Перевод выполнен

TMSberBankCard2Card: СберБанк
TMTinkoffBankCard2Card: Тинькофф Банк
TMAlphaBankCard2Card: Альфа Банк
TMPayPalTransfer: PayPal
TMQiwi: Qiwi кошелёк
TMCryptoTransfer: Перевод

BlackList: Чёрный список
PrizmBlackListTitle: Список Prizm-кошельков, уличённых в мощеничестве

Info: Инфо
InfoListTitle: Информация
Alias: Ссылка
Title: Заголовок
ArticeContent: Текст статьи
NewArticle: Новая статья

TermsOfUse: Правила
TermsOfUseTitle: Правила пользования сервисом


WalletAddress: Адрес кошелька
Card: Карта
Phone: Телефон
Skype: Skype
TelegramTitle: Telegram
WebSite: сайт
VkComTitle: ВКонтакте