User: Пользователь

MyOrders: Мои ордера
Execute: Исполнить
Executed: Исполнено
IExchange: Обмениваю
Recieved: Получено
Remainder: Остаток
Rate: Ставка
AllOrders: Все ордера
ActiveOrders: Активные
ExecutedOrders: Выполненые

DateCreated: Дата создания

ProcessRequest: Обработать запрос
TransferMethod: Способ перевода
ExpectedCalculation: Ожидаемый расчёт
ActualCalculation: Расчёт по факту

DespoitRequestAcceptFormStatsTitle: Расчёт заявки

WithdrawalExecuted: Перевод выполнен