# Values formatted like "_env:YESOD_ENV_VAR_NAME:default_value" can be overridden by the specified environment variable.
# See https://github.com/yesodweb/yesod/wiki/Configuration#overriding-configuration-values-with-environment-variables

static-dir:     "_env:YESOD_STATIC_DIR:static"
host:           "_env:YESOD_HOST:*4" # any IPv4 host
# port:           "_env:YESOD_PORT:3000" # NB: The port `yesod devel` uses is distinct from this value. Set the `yesod devel` port from the command line.
port:           "_env:PORT:3000" # NB: The port `yesod devel` uses is distinct from this value. Set the `yesod devel` port from the command line.
ip-from-header: "_env:YESOD_IP_FROM_HEADER:false"

# Default behavior: determine the application root from the request headers.
# Uncomment to set an explicit approot
#approot:        "_env:YESOD_APPROOT:http://localhost:3000"

# By default, `yesod devel` runs in development, and built executables use
# production settings (see below). To override this, use the following:
#
# development: false

# Optional values with the following production defaults.
# In development, they default to the inverse.
#
# detailed-logging: true
should-log-all: true
# reload-templates: false
# mutable-static: false
# skip-combining: false
# auth-dummy-login : false

# NB: If you need a numeric value (e.g. 123) to parse as a String, wrap it in single quotes (e.g. "_env:YESOD_PGPASS:'123'")
# See https://github.com/yesodweb/yesod/wiki/Configuration#parsing-numeric-values-as-strings

database:
  user:     "_env:YESOD_PGUSER:prizm_exchange"
  password: "_env:YESOD_PGPASS:dr89MkRu37@6"
  host:     "_env:YESOD_PGHOST:188.225.74.136"
  port:     "_env:YESOD_PGPORT:5432"
  # See config/test-settings.yml for an override during tests
  # database: "_env:YESOD_PGDATABASE:prizm-exchange"
  database: "_env:YESOD_PGDATABASE:fenix_trading"
  poolsize: "_env:YESOD_PGPOOLSIZE:10"

copyright: © 2018-2019
#analytics: UA-YOURCODE

ref-token-param-name: "ref"
ref-max-levels: 10

# possible options are: fenix | outbirds
app-type: fenix
ref-token-cookie-name: "_fnx_ref"
# app-type: outbirds
# ref-token-cookie-name: "_outb_ref"